### ISSUE TITLE
Make --fast really fast

### ISSUE THREAD

**Issue by serhiy-storchaka** [vstinner/perf#28]
The main reason why I use the standard `timeit` module instead of `perf timeit` -- it is fast. I get a result in 1-2 sec. In contrary, `perf timeit` even with the `--fast` option takes at least 10 sec. It is too slow when you are experimenting and run a microbenchark after every tiny change. The precision of the standard `timeit` module is enough if the difference is tens or hundreds percents.

The `--fast` option would be more useful if it decrease benchmarking time to 1-2 sec.

**Comment by haypo** [comment]
I dislike the --fast option. I would prefer to remove it.

In 2 seconds, what you get from timeit is "one result" but not "the good
result". With too few processes, you will likely fall in a minimum local
trap.

If you really want a result in 2 seconds, I would prefer a more explicit
option name like --quick-and-dirty, --unreliable or something like that.

If you want to keep --fast but use less processes, another option is to
display a warning. I would be fine if "perf check" complains if it has too
few runs or too few total values.

For example, --debug-single-value should emit a warning sinxe it uses a
single value and a single process.

**Comment by vstinner** [comment]
I'm not sure what to do with this issue. In case of doubt, I close it. Reopen it if you still want to change something.
