### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by ngoldbaum** [vstinner/perf#44]
Do you have any preference for how I should cite perf? I'm using it to write a paper where I will be benchmarking my library against competitors.

I'm happy to just cite the github repo but perhaps there's something else I should be citing.

**Comment by vstinner** [comment]
Whatever works.

**Comment by vstinner** [comment]
If you have anything to propose, go ahead. In the meanwhile, I'm perfectly fine with using the GitHub URL or http://perf.readthedocs.io/ :-)

**Comment by ngoldbaum** [comment]
If you care (perhaps you don't, only academics seem to prize official tracked citation counts), you could write an article in a venue like the [Journal of Open Source Software](https://joss.theoj.org/) which will create a citeable artifact. The paper need only be a paragraph or two and `perf` already satisfies the documentation and code quality metrics in the JOSS reviewer guidelines.

You could also upload releases to e.g. zenodo to generate a citeable DOI for each release.

It looks like I ended up just using the github URL:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/3126246/51043657-d7afcd80-1584-11e9-867f-121649ffad52.png">

**Comment by vstinner** [comment]
I'm a little bit from the academic world. You can do it if you want ;-)
