### ISSUE TITLE
Handling "ERROR: failed to calibrate the number of warmups"

### ISSUE THREAD

**Issue by ngoldbaum** [vstinner/perf#45]
I see in the source code that this is generated when the number of warmups exceeds a hard-coded value of 300. I'm doing some benchmarks under pypy and I guess the JIT warmup is an issue and this particular benchmark needs more warmups to converge.

How would you suggest I handle this? It looks like the maximum number of warmups is hard-coded - would you be ok with taking a patch that makes it configurable? Or maybe it is configurable already and I'm missing the parameter.

Thanks!

**Comment by vstinner** [comment]
The PyPy support of perf is still experimental :-( The calibration of a benchmark for a JIT compiler is a very complex issue. See:
http://vstinner.readthedocs.io/pypy_warmups.html#goal

> Or maybe it is configurable already and I'm missing the parameter.

The calibration chooses two values: number of warmups and number of loops. You can specify both on the command line: pypy mybench.py --loops=5 --warmups=3

Use --help for more options, or see this documentation:
http://perf.readthedocs.io/en/latest/runner.html

**Comment by ngoldbaum** [comment]
Thanks! That explains things.
