### ISSUE TITLE
Environment variables are not inherited

### ISSUE THREAD

**Issue by jdemeyer** [vstinner/perf#47]
For unclear reasons, `perf` removes all environment variables except for a specific white-list. I consider this a bug: environment variables are generally meant to be passed to all subprocesses.

**Comment by vstinner** [comment]
It is a deliberate choice to make results more reproducible between two
computers. There is a command line option to copy some variables.

If you want, you can implement a new option to opt-in to inherit the whole
environement.

**Comment by jdemeyer** [comment]
> It is a deliberate choice to make results more reproducible between two computers.

How does blocking environment variables achieve that?

The only situation where such a blanket block of environment variables makes sense is for security reasons and that doesn't apply here. Another reason is changing/removing specific known-broken environment variables, but I don't think that this applies here either. In any case, the latter calls for a blacklist, not a whitelist.

I think that `perf` should run commands exactly the same way as in the usual Python environment. I don't see any reason to change environment variables at all, so whatever options are implemented, keeping the environment as-is should be the default.

**Comment by vstinner** [comment]
> How does blocking environment variables achieve that?

For example, if you install a Python module on your machine and it's in the PYTHONPATH, the module can slowdown the benchmark, whereas the same benchmark on a similar machine without this module may be faster. Or it can be the opposite.

It's common that environment variables control optional features.

**Comment by vstinner** [comment]
@jdemeyer it's unclear to me if you still need to inherit the full environment or not. In case of doubt, I close the issue. If you want to move this forward, you can try to implement a change to add an option to implement that.

**Comment by jdemeyer** [comment]
I still think that it's a bug in `perf` that environment variables are blocked. But to be honest, I don't care enough to make a PR myself.

**Comment by vstinner** [comment]
Just one example. Depending on PYTHONPATH, you may or may not get additional .pth files which can change the behavior and impact performances.

**Comment by jdemeyer** [comment]
> Depending on PYTHONPATH, you may or may not get additional .pth files which can change the behavior and impact performances.

Right, but that's a *feature*! I don't want code to suddenly behave differently if it's being profiled by `perf`. Instead, `perf` should just run the code that would normally be run by Python. If I set a `PYTHONPATH`, it means that I want to use it.

**Comment by vstinner** [comment]
(I reopen the discussion.)

perf helps you to identify what's unusal in your benchmark configuration to get reproducible results.

Removing environment variables idea comes from the old Python Grand Unified Benchmark Suite which late became http://pyperformance.readthedocs.io/ : new implementation (written by me) based on perf.
